openapi: 3.0.0
info:
  title: Time API
  version: 1.0.0
servers:
  - url: 'http://localhost:8000/webapp'
    description: local dev server
paths:
  /time/:
    get:
      operationId: time
      summary: return current time
      responses:
        '200':
          description: the request was succeed
          content:
            application/json:
              examples:
                time:
                  value:
                    time: '13:28'
